INSERT INTO CodigoBarras (tipo, valor, fechaAsignacion, observaciones, eliminado)
SELECT
    CASE 
        WHEN RAND() < 0.33 THEN 'EAN13'
        WHEN RAND() < 0.66 THEN 'EAN8'
        ELSE 'UPC'
    END AS tipo,
    CONCAT(
        CASE 
            WHEN RAND() < 0.33 THEN 'EAN13' 
            WHEN RAND() < 0.66 THEN 'EAN8' 
            ELSE 'UPC' 
        END,
        LPAD(@row := @row + 1, 7, '0')
    ) AS valor,
    DATE_ADD('2020-01-01', INTERVAL FLOOR(RAND()*1000) DAY) AS fechaAsignacion,
    CONCAT('Observación ', @row) AS observaciones,
    FALSE AS eliminado
FROM (
    SELECT 0
    FROM
        (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4) a,
        (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4) b,
        (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4) c,
        (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4) d,
        (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4) e,
        (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4) f,
        (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4) g,
        (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4) h,
		(SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4) i
) AS big,
(SELECT @row := 0) r
LIMIT 100000;
