nombre=input("Ingrese su Nombre ")
apellido=input("Ingrese su apellido ")  
edad=int(input("Ingrese su edad "))
residencia=input("Ingrese su lugar de residencia ")
print(f"Soy {nombre} {apellido}, tengo {edad} años y vivo en {residencia}")